version: "3"

services:

  mysql:
    container_name: expressplate_mysql
    build: 
      context: ./docker
      dockerfile: Dockerfile_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - 13306:3306

  express:
    container_name: expressplate_express
    build: 
      context: ./docker
      dockerfile: Dockerfile_express
    ports: 
      - 1337:1337
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./:/www"
      - "/www/node_modules"
    stdin_open: true
