FROM mysql:8

# 基本
ARG base_timezone="Asia/Tokyo"
# mysql
ARG dbpass="password"
ARG dbname="database"

# 基本 ###################################
# locale設定
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

# timezone設定
ENV TZ="${base_timezone}"

# mysql ###################################
ENV MYSQL_ROOT_PASSWORD="${dbpass}"
RUN echo "create database ${dbname};" >> /docker-entrypoint-initdb.d/createdb.sql

# ポート解放
EXPOSE 3306
